#!/usr/bin/env sh

STAGED_FILES=$(git diff --cached --name-only)

if [ -z "$STAGED_FILES" ]; then
  echo "⚠️ No staged files found."
  exit 0
fi

echo "🔍 Running lint-staged..."

npx lint-staged

if [ $? -ne 0 ]; then
  echo "❌ Pre-commit failed."
  exit 1
fi

echo "✅ Pre-commit passed."